### ISSUE TITLE
force harmonic

### ISSUE THREAD

**Issue by connerphlip** [youliangzhu/pygamd-v1#1]
```python
def cu_bond(force_name):
	@cuda.jit(device=True)
	def _harmonic(rsq, param, fp):
		k = param[0]
		r0 = param[1]
		r = math.sqrt(rsq)
		f = k * (r0/r - nb.float32(1.0))
		p = nb.float32(0.5) * k * (r0 - r) * (r0 - r)
		fp[0]=f
		fp[1]=p

	if force_name=="harmonic":
		return _harmonic
		
```
代码第七行的弹簧力是不是应该改成
```python
f = k * (r0-r )
```
对于
```python
f = k * (r0/r - nb.float32(1.0))
```
无论r取多大值（0以外），f都是一个定值-k(如您程序中所给定的r0=0来计算的话），弹簧力应该是距离越远，力越大才对呀，还是说这个力应该一直取定值？
希望您能解答我的疑惑。
谢谢！

**Comment by youliangzhu** [comment]
谢谢，这里力的表达式中多出来的1/r是力的方向向量（dx/r, dy/r, dz/r）中的1/r，被提前到这里合并运算了，在自定义函数中给出了force和potential的表达式，其中force的表达式也是多出了1/r



***@***.***
 
From: connerphlip
Date: 2022-09-21 16:57
To: youliangzhu/pygamd-v1
CC: Subscribed
Subject: [youliangzhu/pygamd-v1] force harmonic (Issue #1)
def cu_bond(force_name):
	@cuda.jit(device=True)
	def _harmonic(rsq, param, fp):
		k = param[0]
		r0 = param[1]
		r = math.sqrt(rsq)
		f = k * (r0/r - nb.float32(1.0))
		p = nb.float32(0.5) * k * (r0 - r) * (r0 - r)
		fp[0]=f
		fp[1]=p
	if force_name=="harmonic":
		return _harmonic
		
代码第七行的弹簧力是不是应该改成
f = k * (r0-r )
对于
f = k * (r0/r - nb.float32(1.0))
无论r取多大值（0以外），f都是一个定值-k(如您程序中所给定的r0=0来计算的话），弹簧力应该是距离越远，力越大才对呀，还是说这个力应该一直取定值？
希望您能解答我的疑惑。
谢谢！

**Comment by connerphlip** [comment]
懂了，非常感谢！
